# SPDX-License-Identifier: GPL-3.0-or-later
"""
Type definitions for DaVinci Resolve API.

This module provides Protocol definitions for the DaVinci Resolve API
to improve type safety while working with the external scripting interface.
"""

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DaVinciProject(Protocol):
    """Protocol for DaVinci Resolve Project objects."""

    def GetName(self) -> str:
        """Get the project name."""
        ...

    def GetTimelines(self) -> list[Any]:
        """Get all timelines in the project."""
        ...

    def GetCurrentTimeline(self) -> Any | None:
        """Get the currently active timeline."""
        ...

    def AddTimeline(self, name: str) -> Any | None:
        """Add a new timeline with the given name."""
        ...

    def GetMediaPool(self) -> Any:
        """Get the media pool for this project."""
        ...


@runtime_checkable
class DaVinciTimeline(Protocol):
    """Protocol for DaVinci Resolve Timeline objects."""

    def GetName(self) -> str:
        """Get the timeline name."""
        ...

    def GetTrackCount(self, track_type: str) -> int:
        """Get the number of tracks of the specified type."""
        ...


@runtime_checkable
class DaVinciMediaPool(Protocol):
    """Protocol for DaVinci Resolve MediaPool objects."""

    def GetClips(self) -> list[Any]:
        """Get all clips in the media pool."""
        ...

    def ImportMedia(self, file_path: str) -> bool:
        """Import media from the specified file path."""
        ...


@runtime_checkable
class DaVinciProjectManager(Protocol):
    """Protocol for DaVinci Resolve ProjectManager objects."""

    def GetCurrentProject(self) -> DaVinciProject | None: ...
    def GetProjectListInCurrentFolder(self) -> list[str]: ...
    def CreateProject(self, name: str) -> DaVinciProject | None: ...
    def LoadProject(self, name: str) -> DaVinciProject | None: ...
    def CloseProject(self, project: Any) -> bool: ...
    def DeleteProject(self, name: str) -> bool: ...
    def ExportProject(
        self, name: str, file_path: str, with_stills_and_luts: bool
    ) -> bool: ...
    def ImportProject(self, file_path: str, project_name: str) -> bool: ...
    def ArchiveProject(
        self,
        name: str,
        file_path: str,
        src_media: bool,
        render_cache: bool,
        proxy_media: bool,
    ) -> bool: ...
    def RestoreProject(self, file_path: str, project_name: str) -> bool: ...
    def GetProjectAttributesInCurrentFolder(self) -> Any: ...
    def CreateFolder(self, folder_name: str) -> bool: ...
    def DeleteFolder(self, folder_name: str) -> bool: ...
    def GetFolderListInCurrentFolder(self) -> list[str]: ...
    def GetCurrentFolder(self) -> Any: ...
    def OpenFolder(self, folder_name: str) -> bool: ...
    def GotoRootFolder(self) -> bool: ...
    def GotoParentFolder(self) -> bool: ...
    def GetDatabaseList(self) -> list[Any]: ...
    def GetCurrentDatabase(self) -> Any: ...
    def SetCurrentDatabase(self, db_info: dict[str, Any]) -> bool: ...


@runtime_checkable
class DaVinciResolveApp(Protocol):
    """Protocol for the main DaVinci Resolve application object."""

    def GetVersion(self) -> list[str]: ...
    def GetProductName(self) -> str: ...
    def GetVersionString(self) -> str: ...
    def GetProjectManager(self) -> DaVinciProjectManager: ...
    def GetCurrentPage(self) -> str: ...
    def OpenPage(self, page: str) -> bool: ...
    def GetCurrentProject(self) -> DaVinciProject | None: ...
    def GetMediaStorage(self) -> Any: ...


# Type aliases for common return types
ResolveVersion = list[str]
ProjectName = str
TimelineName = str
PageName = str
MediaClipInfo = dict[str, Any]
